import { DeskActivity } from '@/app/types/activity';

export const MOCK_ACTIVITIES: DeskActivity[] = [
  {
    id: "054f2de3-f6da-49f3-9e3c-5e7b5ae7195a",
    created_at: "2026-05-04T14:59:43.971Z",
    updated_at: "2026-05-04T14:59:43.971Z",
    list_id: "capture",
    status: "new",
    source: "manual",
    snooze_until: "",
    last_triaged_at: "",
    triage_notes: "",
    file_url: "",
    file: null,
    preview_url: "",
    title: "Mingle x Papote: the parent social",
    description: "Mingle Community and Papote present a gezellige vrijmibo, a social event for international parents and parents-to-be in Amsterdam. This gathering combines Dutch practice with socializing, offering a relaxed environment to make new connections and enjoy drinks. If you're not familiar with 'vrijmibo', this is the perfect opportunity to find out! The event includes access to a play area, and all Dutch language levels are welcome.",
    url: "https://tupkertaaltraining.plugandpay.com/checkout/mingle-x-papote-the-parent-social",
    organization: "Mingle Community & Papote",
    age_range: "",
    categories: [],
    newsletter_description: "Mingle Community and Papote host 'Mingle x Papote: the parent social,' a gezellige vrijmibo for international parents and parents-to-be in Amsterdam. This social gathering offers a relaxed environment to practice Dutch, enjoy drinks, and connect with other parents. All Dutch language levels are welcome, and a play area is included.",
    newsletter_last: "",
    newsletter_highlight: false,
    location: "Vasco da Gamastraat 65, 1056 RE Amsterdam, Netherlands",
    neighborhood: "De Baarsjes",
    area: "West",
    
    // Event specific properties (mapped to safe non-null values)
    start_date: "2026-05-08",
    end_date: "2026-05-08",
    start_time: "17:45:00",
    end_time: "19:15:00",
    day_of_week: "Friday",
    duration_minutes: 90,
    repeat_rrule: "",
    repeat_frequency: null, // Dropdown friendly
    repeat_next_date: "",
    calendar_skip: false,
    calendar_sent: false
  },
  {
    id: "054f2de3-f6da-49f3-9e3c-5e7b5ae7195b",
    created_at: "2026-05-04T14:59:43.971Z",
    updated_at: "2026-05-04T14:59:43.971Z",
    list_id: "review",
    status: "new",
    source: "manual",
    snooze_until: "",
    last_triaged_at: "",
    triage_notes: "",
    file_url: "",
    file: null,
    preview_url: "",
    title: "Papote Café",
    description: "A café built for life with kids",
    url: "https://papotecafe.com/",
    organization: "Mingle Community & Papote",
    age_range: "",
    categories: [],
    newsletter_description: "",
    newsletter_last: "",
    newsletter_highlight: false,
    location: "Vasco da Gamastraat 65, 1056 RE Amsterdam, Netherlands",
    neighborhood: "De Baarsjes",
    area: "West",
  },
  {
    id: "a3b2c1d0-e9f8-4a7b-8c9d-0e1f2a3b4c5d", // Generated dynamic fallback UUID
    created_at: "2026-04-25T09:30:00.000Z",
    updated_at: "2026-04-25T09:30:00.000Z",
    list_id: "upcoming_events",
    status: "new",
    source: "app_desk",
    snooze_until: "",
    last_triaged_at: "",
    triage_notes: "",
    file_url: "",
    file: null,
    preview_url: "",
    title: "Dads Do Art @ OBA Osdorp",
    description: "Join us on Saturday April 25th for another fun and creative series with Liam from Dads Do Art, a local project that encourages dads to connect with their kids through creativity.\nTogether, we’ll explore playful art activities designed for toddlers and their adults to enjoy side by side. These sessions are about bonding, expression, and discovering the joy of making something together.\nWhile we especially encourage dads to join, everyone is warmly welcome: mums, grandparents, caregivers, and friends alike.\nExpect a relaxed, friendly space where creativity flows, connections grow, and every splash of paint tells a story.\nNo art experience needed (but if you are more artistically-inclined and want to help an enthusiastic idiot out, then please chat to me after the event as I'd love to see if we could collaborate) just curiosity and a smile!",
    url: "https://luma.com/t4uxe16j",
    organization: "Dads Do Art",
    age_range: "1-3 years",
    categories: [],
    newsletter_description: "Join Dads Do Art with Liam Moclair at OBA Osdorp for a fun and creative session designed for toddlers and their adults (though everyone is welcome!). This free event focuses on bonding, expression, and discovering the joy of making something together, no art experience required. For ages 1-3 years.",
    newsletter_last: "",
    newsletter_highlight: false,
    location: "Osdorpplein 16, 1068 EL Amsterdam, Netherlands",
    neighborhood: "Osdorp",
    area: "West",
    
    // CamelCase mappings to snake_case schema fields
    start_date: "2026-04-25",
    end_date: "2026-04-25",
    start_time: "09:30",
    end_time: "11:00",
    day_of_week: "Saturday",
    duration_minutes: 90,
    repeat_rrule: "",
    repeat_frequency: null,
    repeat_next_date: "",
    calendar_skip: false,
    calendar_sent: false
  }
];