import { DeskActivity } from '@/app/types/activity';

export const MOCK_ACTIVITIES: DeskActivity[] = [
  {
    id: "054f2de3-f6da-49f3-9e3c-5e7b5ae7195a",
    created_at: "2026-05-04T14:59:43.971Z",
    updated_at: "2026-05-04T14:59:43.971Z",
    list_id: "capture",
    status: "new",
    source: "manual",
    snooze_until: "",
    last_triaged_at: "",
    triage_notes: "",
    file_url: "",
    file: null,
    preview_url: "",
    title: "Mingle x Papote: the parent social",
    description: "Mingle Community and Papote present a gezellige vrijmibo, a social event for international parents and parents-to-be in Amsterdam. This gathering combines Dutch practice with socializing, offering a relaxed environment to make new connections and enjoy drinks. If you're not familiar with 'vrijmibo', this is the perfect opportunity to find out! The event includes access to a play area, and all Dutch language levels are welcome.",
    url: "https://tupkertaaltraining.plugandpay.com/checkout/mingle-x-papote-the-parent-social",
    organization: "Mingle Community & Papote",
    age_range: "",
    categories: [],
    newsletter_description: "Mingle Community and Papote host 'Mingle x Papote: the parent social,' a gezellige vrijmibo for international parents and parents-to-be in Amsterdam. This social gathering offers a relaxed environment to practice Dutch, enjoy drinks, and connect with other parents. All Dutch language levels are welcome, and a play area is included.",
    newsletter_last: "",
    newsletter_highlight: false,
    location: "Vasco da Gamastraat 65, 1056 RE Amsterdam, Netherlands",
    neighborhood: "De Baarsjes",
    area: "West",
    
    // Event specific properties (mapped to safe non-null values)
    start_date: "2026-05-08",
    end_date: "2026-05-08",
    start_time: "17:45:00",
    end_time: "19:15:00",
    day_of_week: "Friday",
    duration_minutes: 90,
    repeat_rrule: "",
    repeat_frequency: null, // Dropdown friendly
    repeat_next_date: "",
    calendar_skip: false,
    calendar_sent: false
  },
  {
    id: "054f2de3-f6da-49f3-9e3c-5e7b5ae7195b",
    created_at: "2026-05-04T14:59:43.971Z",
    updated_at: "2026-05-04T14:59:43.971Z",
    list_id: "review",
    status: "new",
    source: "manual",
    snooze_until: "",
    last_triaged_at: "",
    triage_notes: "",
    file_url: "",
    file: null,
    preview_url: "",
    title: "Papote Café",
    description: "A café built for life with kids",
    url: "https://papotecafe.com/",
    organization: "Mingle Community & Papote",
    age_range: "",
    categories: [],
    newsletter_description: "",
    newsletter_last: "",
    newsletter_highlight: false,
    location: "Vasco da Gamastraat 65, 1056 RE Amsterdam, Netherlands",
    neighborhood: "De Baarsjes",
    area: "West",
  }
];