import { DeskActivity } from "./types/activity";

export const MOCK_ACTIVITIES: DeskActivity[] = [
  {
    id: "evt-001",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    list_id: "review",
    status: "new",
    source: "app_desk",
    title: "Community Plant Swap & Social",
    description: "Bring your extra propagation cuttings, starter plants, or pots to swap with neighbors! All skill levels welcome.",
    newsletter_description: "Join your neighbors this weekend for the annual spring plant swap! Great opportunity to pick up new greenery and tips.",
    categories: ["community", "gardening"],
    file_url: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&q=80&w=400", // Simulated Supabase URL
    file: null,
    preview_url: null,
    url: "https://example.com/events/plant-swap",
    organization: "Green Thumb Collective",
    age_range: "All Ages",
    location: "Snyder Park Pavilion",
    neighborhood: "Northside",
    area: "Zone 2",
    snooze_until: null,
    last_triaged_at: null,
    triage_notes: null,
    newsletter_last: null,
    newsletter_highlight: true,
  },
  {
    id: "evt-002",
    created_at: new Date().toISOString(), // Just now
    updated_at: new Date().toISOString(),
    list_id: "capture",
    status: "new",
    source: "app_desk",
    title: "✨ Processing...",
    description: "Screenshot upload from user of a flyer on a telephone pole about a neighborhood cleanup next Saturday at 9 AM.",
    newsletter_description: "AI is generating a summary...",
    categories: [],
    file_url: null,
    // Simulating an active in-flight upload on the client
    file: new File([""], "screenshot.png", { type: "image/png" }), 
    preview_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=400", // Acting as local blob URL
    url: null,
    organization: null,
    age_range: null,
    location: null,
    neighborhood: null,
    area: null,
    snooze_until: null,
    last_triaged_at: null,
    triage_notes: null,
    newsletter_last: null,
    newsletter_highlight: false,
  },
  {
    id: "evt-003",
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2 hours ago
    updated_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    list_id: "capture",
    status: "new",
    source: "app_desk",
    title: "Kids Coding Workshop Flyer",
    description: "Snapped a photo of the local library bulletin board. Intro to Scratch coding for elementary students.",
    newsletter_description: "An introductory programming class for young minds, leveraging block-based visual tools.",
    categories: ["education", "kids"],
    // Successfully processed: file uploaded to Supabase, local files cleared out
    file_url: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=400",
    file: null,
    preview_url: null,
    url: null,
    organization: "Downtown Public Library",
    age_range: "7-11",
    location: "Library Lab Room B",
    neighborhood: "Downtown",
    area: "Zone 1",
    snooze_until: null,
    last_triaged_at: null,
    triage_notes: "Needs verification on maximum class capacity.",
    newsletter_last: null,
    newsletter_highlight: false,
  },
  {
    id: "evt-004",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    list_id: "error",
    status: "snoozed",
    source: "manual",
    title: "Summer Concert Series Lineup Announced",
    description: "Link to the city portal showing the upcoming band lineup starting in June.",
    newsletter_description: "",
    categories: ["music", "free"],
    file_url: null,
    file: null,
    preview_url: null,
    url: "https://cityportal.gov/summer-music",
    organization: "Parks & Recreation Dept",
    age_range: "All Ages",
    location: "Amphitheater",
    neighborhood: "Waterfront",
    area: "Zone 4",
    snooze_until: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(), // Snoozed for 1 week
    last_triaged_at: new Date().toISOString(),
    triage_notes: "Snoozed until closer to the summer season kick-off.",
    newsletter_last: null,
    newsletter_highlight: false,
  }
];